export const noteConstants = {
  GET_REQUEST: 'GET_NOTES_REQUEST',
  GET_SUCCESS: 'GET_NOTES_SUCCESS',
  GET_FAILURE: 'GET_NOTES_FAILURE',

  ADD_REQUEST: 'ADD_NOTE_REQUEST',
  ADD_SUCCESS: 'ADD_NOTE_SUCCESS',
  ADD_FAILURE: 'ADD_NOTE_FAILURE',

  EDIT_REQUEST: 'EDIT_NOTE_REQUEST',
  EDIT_FAILURE: 'EDIT_NOTE_FAILURE',

  DELETE_REQUEST: 'DELETE_NOTE_REQUEST',
  DELETE_SUCCESS: 'DELETE_NOTE_SUCCESS',
  DELETE_FAILURE: 'DELETE_NOTE_FAILURE',
};
